# Generated by Django 3.1.7 on 2021-04-05 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Тема')),
                ('description', models.TextField(verbose_name='Описание')),
                ('urls', models.SlugField(max_length=160, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Userr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_login', models.PositiveIntegerField(default=0, verbose_name='ID')),
                ('balls', models.PositiveIntegerField(default=0, verbose_name='Баллы')),
            ],
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Слово')),
                ('translate', models.CharField(max_length=30, verbose_name='Перевод')),
                ('example', models.CharField(max_length=100, verbose_name='Пример')),
                ('id_topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wordsapp.topic')),
            ],
        ),
        migrations.CreateModel(
            name='Synonym',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Синоним')),
                ('id_word', models.ManyToManyField(related_name='word_syn', to='wordsapp.Word', verbose_name='Синоним')),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=1)),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wordsapp.userr')),
                ('id_word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wordsapp.word')),
            ],
        ),
    ]
