# Generated by Django 3.1.7 on 2021-04-09 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wordsapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='state',
            name='status',
            field=models.BooleanField(),
        ),
    ]
