# Generated by Django 3.1.7 on 2021-05-15 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wordsapp', '0002_auto_20210515_1043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
    ]
